# Generated by Django 5.1.4 on 2024-12-24 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajosTerminales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('numero_tt', models.CharField(max_length=13)),
                ('asesores', models.TextField()),
                ('sinodales', models.TextField()),
                ('escrito', models.FileField(upload_to='archivos/')),
                ('anio', models.PositiveBigIntegerField()),
                ('palabras_clave', models.TextField()),
                ('resumen', models.TextField()),
                ('autores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Trabajos_Terminales',
            },
        ),
    ]
