# Generated by Django 5.1.4 on 2024-12-24 02:07

import apps.vincula_tt.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincula_tt', '0002_alter_trabajosterminales_escrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajosterminales',
            name='escrito',
            field=models.FileField(upload_to='archivos/', validators=[apps.vincula_tt.validation.validate_file_size, apps.vincula_tt.validation.validate_file_extension]),
        ),
    ]
