# Generated by Django 5.1.4 on 2024-12-27 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincula_tt', '0003_alter_trabajosterminales_escrito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajosterminales',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_terminales', to=settings.AUTH_USER_MODEL),
        ),
    ]
